spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/hangbokwatch
      username: kyun
      password: pass
      driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc.lob.non_contextual_creation: true
    show-sql: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  h2:
    console:
      enabled: true
  HWresource:
    HWimages: /Users/kyun/workspace/HangbokWatch_Project/HangbokWatch_Resource/HWimages/

logging:
  file:
    max-history: 5
    name: /Users/kyun/workspace/HangbokWatch_Project/HangbokWatch_Resource/LOGS/spring.log
  level:
    root: info
    com.hangbokwatch.backend.service: debug
    com.hangbokwatch.backend.job: debug
    org.hibernate: error
    sql: info

# 운영환경
---
spring:
  profiles: production


