spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc.lob.non_contextual_creation: true

# local 환경
---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/hangbokwatch
    username: kyun
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  h2:
    console:
      enabled: true