spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc.lob.non_contextual_creation: true

# local 환경
---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/hangbokwatch
    username: kyun
    password: pass
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  h2:
    console:
      enabled: true
  HWresource:
    HWimages: /Users/kyun/workspace/HangbokWatch_Project/HangbokWatch_Resource/HWimages/

logging:
  file:
    max-history: 5
    name: /Users/kyun/workspace/HangbokWatch_Project/HangbokWatch_Resource/LOGS/spring.log
  level:
    root: info
    com.hangbokwatch.backend.service: debug
    org.hibernate: error
    sql: error

# 운영환경
---
spring:
  profiles: production


